parameters: ~

services:
    twig.extension.acme.demo:
        class: Acme\DemoBundle\Twig\Extension\DemoExtension
        arguments:
            - @twig.loader
        tags:
            - { name: twig.extension }
    acme.demo.listener:
        class: Acme\DemoBundle\EventListener\ControllerListener
        arguments:
            - @twig.extension.acme.demo
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    acme.demo.repository.product:
        class: Acme\DemoBundle\Entity\Repository\ProductRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['AcmeDemoBundle:Product']

