Acme\DemoBundle\Entity\Product:
    type: entity
    table: demo_product
    repositoryClass: Acme\DemoBundle\Entity\Repository\ProductRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        sku:
            type: string
            length: 20
            unique: true

